#!/usr/bin/env php
<?php
$phake_file = 'PhakeFile';

if(!file_exists($phake_file)){
    echo "PhakeFile not found! \n";
    exit();
}

$action = isset($argv[1]) ? $argv[1] : '_default';

require_once($phake_file);

if(function_exists($action))
    eval("$action();");
else
    echo "task not found: '$action' \n";

?>